adsense_plugin:
  adsense_publisher_code:
    client: true
    default: ''
  adsense_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  adsense_topic_list_top_code:
    client: true
    default: ''
  adsense_mobile_topic_list_top_code:
    client: true
    default: ''    
  adsense_show_topic_list_top:
    client: true
    default: false
  adsense_topic_list_top_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  adsense_topic_above_post_stream_code:
    client: true
    default: ''
  adsense_mobile_topic_above_post_stream_code:
    client: true
    default: ''    
  adsense_show_topic_above_post_stream:
    client: true
    default: false
  adsense_topic_above_post_stream_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  adsense_topic_above_suggested_code:
    client: true
    default: ''
  adsense_mobile_topic_above_suggested_code:
    client: true
    default: ''
  adsense_show_topic_above_suggested:
    client: true
    default: false
  adsense_topic_above_suggested_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  adsense_post_bottom_code: 
    client: true
    default: ''
  adsense_mobile_post_bottom_code: 
    client: true
    default: ''
  adsense_show_post_bottom:
    client: true
    default: false
  adsense_post_bottom_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
  adsense_nth_post_code: 
    client: true
    default: ''

dfp_plugin:
  dfp_publisher_id:
    client: true
    default: ''
  dfp_through_trust_level:
    client: true
    default: 2
    enum: 'TrustLevelSetting'
  dfp_topic_list_top_code:
    client: true
    default: ''
  dfp_mobile_topic_list_top_code:
    client: true
    default: ''
  dfp_topic_list_top_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  dfp_target_topic_list_top_key_code:    
    default: ''
    type: value_list
    client: true
  dfp_target_topic_list_top_value_code:
    default: ''
    type: value_list
    client: true
  dfp_show_topic_list_top:
    client: true
    default: false
  dfp_topic_above_post_stream_code:
    client: true
    default: ''
  dfp_mobile_topic_above_post_stream_code:
    client: true
    default: ''
  dfp_topic_above_post_stream_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  dfp_show_topic_above_post_stream:
    client: true
    default: false
  dfp_target_topic_above_post_stream_key_code:
    default: ''
    type: value_list
    client: true
  dfp_target_topic_above_post_stream_value_code:
    default: ''
    type: value_list
    client: true
  dfp_topic_above_suggested_code:
    client: true
    default: ''
  dfp_mobile_topic_above_suggested_code:
    client: true
    default: ''  
  dfp_topic_above_suggested_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
      - 125*125 - button 
      - 180*150 - small rectangle
      - 200*200 - small square
      - 250*250 - square
  dfp_show_topic_above_suggested:
    client: true
    default: false
  dfp_target_topic_above_suggested_key_code:
    default: ''
    type: value_list
    client: true
  dfp_target_topic_above_suggested_value_code:
    default: ''
    type: value_list
    client: true
  dfp_post_bottom_code:
    client: true
    default: ''
  dfp_mobile_post_bottom_code:
    client: true
    default: ''  
  dfp_nth_post_code:
    client: true
    default: ''
  dfp_post_bottom_ad_sizes:
    client: true
    default: '728*90 - leaderboard'
    type: enum
    choices:
      - 728*90 - leaderboard
      - 336*280 - large rectangle 
      - 300*250 - medium rectangle
      - 970*90 - large leaderboard
      - 468*60 - banner 
      - 234*60 - half banner 
  dfp_show_post_bottom:
    client: true
    default: false
  dfp_target_post_bottom_key_code:
    default: ''
    type: value_list
    client: true
  dfp_target_post_bottom_value_code:
    default: ''
    type: value_list
    client: true

amazon_plugin:
  amazon_topic_list_top_ad_category:
    client: true
    default: 'Product/Easy Banner Link'
    type: enum
    choices:
      - Product/Easy Banner Link
      - Native Shopping Ad - Recommended
      - Native Shopping Ad - Custom
      - Native Shopping Ad - Search
  amazon_tracking_id_code:
    client: true
    default: ''
  amazon_region_code:
    client: true
    default: ''
  amazon_topic_list_top_src_code:
    client: true
    default: ''
  amazon_topic_list_top_title_code:
    client: true
    default: '' 
  amazon_topic_list_top_ad_width_code:
    client: true
    default: '' 
  amazon_topic_list_top_ad_height_code:
    client: true
    default: ''
  amazon_topic_list_top_custom_product_id_code:
    default: ''
    type: value_list
    client: true
  amazon_topic_list_top_link_id_code:
    client: true
    default: ''
  amazon_topic_list_top_ad_mode:
    client: true
    default: 'manual'
    type: enum
    choices:
      - manual
      - auto
      - search
  amazon_topic_list_top_fallback_mode_value_code:
    client: true
    default: ''
  amazon_topic_list_top_row_ads_code:
    client: true
    default: ''
  amazon_topic_list_top_default_category_code:
    client: true
    default: ''
  amazon_topic_list_top_search_phrase_code:
    client: true
    default: ''
  amazon_through_trust_level:
    client: true
    default: 2  
  amazon_mobile_topic_list_top_src_code:
    client: true
    default: ''
  amazon_mobile_topic_list_top_ad_width_code: 
    client: true
    default: ''
  amazon_mobile_topic_list_top_ad_height_code: 
    client: true
    default: ''
  amazon_topic_above_post_stream_src_code:
    client: true
    default: ''
  amazon_topic_above_post_stream_ad_width_code: 
    client: true
    default: ''
  amazon_topic_above_post_stream_ad_height_code: 
    client: true
    default: ''
  amazon_mobile_topic_above_post_stream_src_code:
    client: true
    default: ''
  amazon_mobile_topic_above_post_stream_ad_width_code:
    client: true
    default: ''
  amazon_mobile_topic_above_post_stream_ad_height_code: 
    client: true
    default: ''
  amazon_topic_above_suggested_src_code: 
    client: true
    default: ''
  amazon_topic_above_suggested_ad_width_code: 
    client: true
    default: ''
  amazon_topic_above_suggested_ad_height_code:
    client: true
    default: ''
  amazon_mobile_topic_above_suggested_src_code:
    client: true
    default: ''
  amazon_mobile_topic_above_suggested_ad_width_code:
    client: true
    default: ''
  amazon_mobile_topic_above_suggested_ad_height_code:
    client: true
    default: ''
  amazon_post_bottom_src_code:
    client: true
    default: ''
  amazon_nth_post_code: 
    client: true
    default: ''
  amazon_post_bottom_ad_width_code:
    client: true
    default: ''
  amazon_post_bottom_ad_height_code:
    client: true
    default: ''
  amazon_mobile_post_bottom_src_code:
    client: true
    default: ''
  amazon_mobile_post_bottom_ad_width_code:
    client: true
    default: ''
  amazon_mobile_post_bottom_ad_height_code:
    client: true
    default: ''