ad_plugin:
  dfp_topic_list_top_code:
    client: true
    default: ''
  dfp_size_topic_list_top_width_code:
    client: true
    default: ''
  dfp_size_topic_list_top_height_code:
    client: true
    default: ''
  dfp_show_topic_list_top:
    client: true
    default: false
  dfp_topic_above_post_stream_code:
    client: true
    default: ''
  dfp_size_topic_above_post_stream_width_code:
    client: true
    default: ''
  dfp_size_topic_above_post_stream_height_code:
    client: true
    default: ''
  dfp_show_topic_above_post_stream:
    client: true
    default: false
  dfp_topic_above_suggested_code:
    client: true
    default: ''
  dfp_size_topic_above_suggested_width_code:
    client: true
    default: ''
  dfp_size_topic_above_suggested_height_code:
    client: true
    default: ''
  dfp_show_topic_above_suggested:
    client: true
    default: false
  dfp_post_bottom_code:
    client: true
    default: ''
  dfp_size_post_bottom_width_code:
    client: true
    default: ''
  dfp_size_post_bottom_height_code:
    client: true
    default: ''
  dfp_show_post_bottom:
    client: true
    default: false
  dfp_show_size_1_example:
    client: true
    default: false
  dfp_show_size_2_example:
    client: true
    default: false
  dfp_show_size_3_example:
    client: true
    default: false
  dfp_show_size_4_example:
    client: true
    default: false
  dfp_show_size_5_example:
    client: true
    default: false
  dfp_show_size_6_example:
    client: true
    default: false
  dfp_show_size_7_example:
    client: true
    default: false
  dfp_show_size_8_example:
    client: true
    default: false
  dfp_show_size_9_example:
    client: true
    default: false
  dfp_show_size_10_example:
    client: true
    default: false

